apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: jaeger-proxy
  name: jaeger-proxy
spec:
  tls:
    termination: reencrypt
  port:
    targetPort: jaeger-proxy
  to:
    kind: Service
    name: jaeger-proxy
    weight: 100
  wildcardPolicy: None
