apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
  name: jaeger-proxy-query
spec:
  ports:
  - name: http-query
    port: 16686
    protocol: TCP
    targetPort: 16686
  selector:
    app: jaeger
{{- if and .Values.is_production_deployment }}
{{ toYaml .Values.services.jaeger_proxy_query.selectors.prod | trim | indent 4 }}
{{- else }}
{{ toYaml .Values.services.jaeger_proxy_query.selectors.dev | trim | indent 4 }}
{{- end }}
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/part-of: jaeger
  sessionAffinity: None
  type: ClusterIP
