
apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: {{ .Values.control_plane_name }}
spec:
  version: v1.1
  istio:
    gateways:
      istio-egressgateway:
        enabled: false
      istio-ingressgateway:
        enabled: false        
      {{ .Values.ingressgateway_name }}:
        enabled: true
        autoscaleEnabled: false
        ior_enabled: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        sds:
          enabled: false
        labels:
          app: {{ .Values.ingressgateway_name }}
          istio: ingressgateway
        type: ClusterIP
        ports:
          - name: status-port
            protocol: TCP
            port: 15020
            targetPort: 15020
          - name: http2
            protocol: TCP
            port: 80
            targetPort: 8080
          - name: https
            protocol: TCP
            port: 443
            targetPort: 8443
          - name: tls
            protocol: TCP
            port: 15443
            targetPort: 15443
    global:
      controlPlaneSecurityEnabled: true
      disablePolicyChecks: false
      mtls:
        enabled: true
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
    grafana:
      enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 128Mi
    kiali:
      enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
    mixer:
      policy:
        autoscaleEnabled: false
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
      telemetry:
        autoscaleEnabled: false
        resources:
          requests:
            cpu: 100m
            memory: 1G
    pilot:
      autoscaleEnabled: false
      traceSampling: 100
      resources:
        requests:
          cpu: 10m
          memory: 128Mi
    tracing:
      enabled: true
      jaeger:
{{- if .Values.is_production_deployment }}      
        template: production-elasticsearch
        elasticsearch:
          nodeCount: 3
          redundancyPolicy: "MultipleRedundancy"
          resources:
            requests:
              cpu: "1"
              memory: "4Gi"
            limits:
              cpu: "1"
              memory: "4Gi"
{{- else }}
        template: all-in-one
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
{{- end }}
